name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: What would you like?
      description: A clear description of the feature you'd like to see
      placeholder: I'd like WebPeel to...
    validations:
      required: true
  - type: textarea
    id: use_case
    attributes:
      label: Use case
      description: How would this help you? What problem does it solve?
      placeholder: This would help me because...
  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - CLI
        - API
        - MCP Server
        - Python SDK
        - Node.js Library
        - Documentation
        - Dashboard
        - Other
    validations:
      required: true
